# Site settings
title: tgb
email: j@cob.email
url: tgb.tools
description: "Collection of Minecraft and Twitch tools"
keywords: "minecraft, twitch, plugins, modding"
skills: "Minecraft Tool Developer"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: tgb

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9368ff #80B3FF
  primary-rgb: "147, 104, 255" #"128,179,255"
  secondary: 9368ff #FD6E8A
  secondary-dark: 9368ff #A2122F

# Footer settings
footer:
  copyright: tgb

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/jacobbashista
  - title: github
    url: https://github.com/tgb20
  - title: youtube
    url: https://youtube.com/orangehaus

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
